version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: andreysmart/foodgram_backend
    env_file: .env.example
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
    depends_on:
      - db

  frontend:
    image: andreysmart/foodgram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
    depends_on:
      - backend

  gateway:
    image: andreysmart/foodgram_gateway
    env_file: .env.example
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles/
      - media_volume:/media/